name: form_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.2.1+1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Thin.ttf
          weight: 100
        - asset: assets/fonts/sarabun/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sarabun/Sarabun-Light.ttf
          weight: 300
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
          weight: 400
        - asset: assets/fonts/sarabun/Sarabun-Medium.ttf
          weight: 500
        - asset: assets/fonts/sarabun/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: assets/fonts/sarabun/Sarabun-ExtraBold.ttf
          weight: 800